import type { Agent, Property, Testimonial } from '@/types/property'
import { formatRWF } from '@/lib/rwanda'
import { imagesForProperty, imageForLocation, agentAvatar } from '@/lib/images'
import { formatRwandaPhone } from '@/lib/phone'

const img = (type: Property['type'], id: string, location: string, n = 3) =>
  imagesForProperty(type, id, n, location)

export const agents: Agent[] = [
  {
    id: 'a1',
    name: 'Marie Uwase',
    avatar: agentAvatar('marie-uwase'),
    phone: formatRwandaPhone('788123456'),
    whatsapp: '788123456',
    rating: 4.9,
    listings: 38,
  },
  {
    id: 'a2',
    name: 'Jean-Pierre Nkurunziza',
    avatar: agentAvatar('jean-pierre'),
    phone: formatRwandaPhone('722987654'),
    whatsapp: '722987654',
    rating: 4.8,
    listings: 24,
  },
  {
    id: 'a3',
    name: 'Grace Ingabire',
    avatar: agentAvatar('grace-ingabire'),
    phone: formatRwandaPhone('739456789'),
    whatsapp: '739456789',
    rating: 5.0,
    listings: 31,
  },
]

export const properties: Property[] = [
  {
    id: 'p1',
    title: 'Kimihurura Executive Villa',
    type: 'house',
    mode: 'buy',
    status: 'available',
    price: 485_000_000,
    currency: 'RWF',
    location: 'Kimihurura',
    city: 'Kigali',
    country: 'Rwanda',
    plotSize: '1,200 m²',
    builtArea: '650 m²',
    bedrooms: 5,
    bathrooms: 6,
    images: img('house', 'p1', 'Kimihurura', 3),
    videoUrl: '#',
    has360Tour: true,
    verified: true,
    trustScore: 98,
    specs: ['Hill view', 'Solar backup', 'Staff quarters', '4-car garage'],
    description:
      'Stunning hillside villa in Kimihurura with panoramic views of Kigali. Fully surveyed plot, RDB-registered title, and premium finishes throughout.',
    survey: {
      plotArea: '1,200 m²',
      dimensions: '40m × 30m',
      boundaries: 'RDB cadastral verified',
      coordinates: { lat: -1.9361, lng: 30.0892 },
      elevation: '1,580m ASL',
    },
    investment: {
      roiForecast: 9.2,
      rentalYield: 6.8,
      appreciationRate: 14.5,
      areaGrowthTrend: '+18% YoY (Kimihurura)',
    },
    agentId: 'a1',
    featured: true,
    ownerName: 'Emmanuel Nshimiyimana',
    ownerPhone: '788765432',
  },
  {
    id: 'h1',
    title: 'Gacuriro Garden Estate',
    type: 'house',
    mode: 'buy',
    status: 'available',
    price: 620_000_000,
    currency: 'RWF',
    location: 'Gacuriro',
    city: 'Kigali',
    country: 'Rwanda',
    plotSize: '1,800 m²',
    builtArea: '720 m²',
    bedrooms: 6,
    bathrooms: 7,
    images: img('house', 'h1', 'Gacuriro', 3),
    has360Tour: true,
    verified: true,
    trustScore: 99,
    specs: ['Infinity pool', 'Smart home', 'Cinema room', '6-car garage'],
    description:
      'Architect-designed estate with resort-style landscaping and panoramic Kigali views. Rwanda\'s most beautiful private residence.',
    survey: {
      plotArea: '1,800 m²',
      dimensions: '45m × 40m',
      boundaries: 'RDB verified',
      coordinates: { lat: -1.928, lng: 30.102 },
    },
    agentId: 'a1',
    featured: true,
    ownerName: 'Claudine Mukamana',
    ownerPhone: '722334455',
  },
  {
    id: 'h2',
    title: 'Nyarutarama Lakeview Manor',
    type: 'house',
    mode: 'buy',
    status: 'available',
    price: 540_000_000,
    currency: 'RWF',
    location: 'Nyarutarama',
    city: 'Kigali',
    country: 'Rwanda',
    plotSize: '1,400 m²',
    builtArea: '580 m²',
    bedrooms: 5,
    bathrooms: 6,
    images: img('house', 'h2', 'Nyarutarama', 3),
    has360Tour: true,
    verified: true,
    trustScore: 98,
    specs: ['Lake view', 'Guest wing', 'Solar + backup', 'Wine cellar'],
    description:
      'Manor-style home overlooking Nyarutarama valley — premium finishes and verified title.',
    agentId: 'a1',
    featured: true,
    ownerName: 'Patrick Mugenzi',
    ownerPhone: '739112233',
  },
  {
    id: 'p2',
    title: 'Kacyiru Skyline Apartment',
    type: 'apartment',
    mode: 'rent',
    status: 'available',
    price: 1_850_000,
    currency: 'RWF',
    location: 'Kacyiru',
    city: 'Kigali',
    country: 'Rwanda',
    builtArea: '185 m²',
    bedrooms: 3,
    bathrooms: 3,
    images: img('apartment', 'p2', 'Kacyiru', 3),
    has360Tour: true,
    verified: true,
    trustScore: 96,
    specs: ['City view', 'Furnished', '24/7 security', 'Parking'],
    description:
      'Modern furnished apartment near government district. Ideal for diplomats and corporate executives.',
    agentId: 'a2',
    featured: true,
  },
  {
    id: 'p3',
    title: 'Kicukiro Prime Development Land',
    type: 'land',
    mode: 'buy',
    status: 'available',
    price: 95_000_000,
    currency: 'RWF',
    location: 'Kicukiro',
    city: 'Kigali',
    country: 'Rwanda',
    plotSize: '2,500 m²',
    images: img('land', 'p3', 'Kicukiro', 3),
    has360Tour: false,
    verified: true,
    trustScore: 94,
    specs: ['G+3 permitted', 'Road access', 'Survey certified', 'Water & power'],
    description:
      'Prime serviced land in fast-growing Kicukiro. Full topographic survey and plot plan available for download.',
    survey: {
      plotArea: '2,500 m²',
      dimensions: '50m × 50m',
      boundaries: 'GIS polygon registered',
      coordinates: { lat: -1.9892, lng: 30.1124 },
      surveyPdfUrl: '#',
    },
    investment: {
      roiForecast: 12.5,
      appreciationRate: 22.0,
      areaGrowthTrend: '+24% YoY (Kicukiro)',
    },
    agentId: 'a3',
    featured: true,
  },
  {
    id: 'p4',
    title: 'CBD Commercial Office Floor',
    type: 'commercial',
    mode: 'buy',
    status: 'under_offer',
    price: 320_000_000,
    currency: 'RWF',
    location: 'Nyarugenge CBD',
    city: 'Kigali',
    country: 'Rwanda',
    builtArea: '420 m²',
    images: img('commercial', 'p4', 'Nyarugenge CBD', 3),
    has360Tour: true,
    verified: true,
    trustScore: 97,
    specs: ['Grade A fit-out', 'Fiber internet', 'Lift access', 'Generator'],
    description: 'Full-floor commercial space in Kigali central business district with turnkey interiors.',
    agentId: 'a1',
    featured: true,
  },
  {
    id: 'p5',
    title: 'Nyarutarama Garden Residence',
    type: 'house',
    mode: 'buy',
    status: 'available',
    price: 275_000_000,
    currency: 'RWF',
    location: 'Nyarutarama',
    city: 'Kigali',
    country: 'Rwanda',
    plotSize: '900 m²',
    builtArea: '480 m²',
    bedrooms: 4,
    bathrooms: 5,
    images: img('house', 'p5', 'Nyarutarama Garden', 3),
    has360Tour: true,
    verified: true,
    trustScore: 99,
    specs: ['Tennis court', 'Pool', 'Smart security', 'Garden'],
    description:
      'Elegant family home in Nyarutarama golf neighborhood. Quiet cul-de-sac with verified land title.',
    survey: {
      plotArea: '900 m²',
      dimensions: '30m × 30m',
      boundaries: 'Beacon-marked & fenced',
      coordinates: { lat: -1.9523, lng: 30.1056 },
    },
    agentId: 'a2',
    featured: true,
  },
  {
    id: 'p6',
    title: 'Remera Family Apartment',
    type: 'apartment',
    mode: 'rent',
    status: 'available',
    price: 950_000,
    currency: 'RWF',
    location: 'Remera',
    city: 'Kigali',
    country: 'Rwanda',
    builtArea: '120 m²',
    bedrooms: 2,
    bathrooms: 2,
    images: img('apartment', 'p6', 'Remera', 2),
    has360Tour: false,
    verified: true,
    trustScore: 91,
    specs: ['Near Amahoro Stadium', 'Balcony', 'Parking'],
    description: 'Bright apartment in vibrant Remera, walking distance to shops and restaurants.',
    agentId: 'a3',
  },
  {
    id: 'p7',
    title: 'Gacuriro Modern Family Home',
    type: 'house',
    mode: 'buy',
    status: 'available',
    price: 198_000_000,
    currency: 'RWF',
    location: 'Gacuriro',
    city: 'Kigali',
    country: 'Rwanda',
    plotSize: '650 m²',
    builtArea: '380 m²',
    bedrooms: 4,
    bathrooms: 4,
    images: img('house', 'p7', 'Gacuriro', 3),
    has360Tour: true,
    verified: true,
    trustScore: 93,
    specs: ['Open plan', 'Study', 'Borehole', 'Electric gate'],
    description: 'Contemporary design in sought-after Gacuriro with full survey documentation.',
    agentId: 'a1',
  },
  {
    id: 'p8',
    title: 'Musanze Tourism Land Parcel',
    type: 'land',
    mode: 'buy',
    status: 'available',
    price: 42_000_000,
    currency: 'RWF',
    location: 'Musanze',
    city: 'Northern Province',
    country: 'Rwanda',
    plotSize: '5,000 m²',
    images: img('land', 'p8', 'Musanze', 3),
    has360Tour: false,
    verified: true,
    trustScore: 92,
    specs: ['Volcanoes view', 'Tourism zone', 'Survey ready'],
    description:
      'Strategic land near Volcanoes National Park — ideal for lodge or eco-resort development.',
    survey: {
      plotArea: '5,000 m²',
      dimensions: '100m × 50m',
      boundaries: 'District land office verified',
      coordinates: { lat: -1.4998, lng: 29.6344 },
      surveyPdfUrl: '#',
    },
    investment: {
      roiForecast: 15.0,
      appreciationRate: 20.0,
      areaGrowthTrend: '+19% YoY (Musanze)',
    },
    agentId: 'a3',
  },
  {
    id: 'p9',
    title: 'Rubavu Lakeside Commercial Plot',
    type: 'commercial',
    mode: 'buy',
    status: 'available',
    price: 156_000_000,
    currency: 'RWF',
    location: 'Rubavu',
    city: 'Western Province',
    country: 'Rwanda',
    plotSize: '1,800 m²',
    images: img('commercial', 'p9', 'Rubavu Lake Kivu', 3),
    has360Tour: false,
    verified: true,
    trustScore: 90,
    specs: ['Lake Kivu frontage', 'Hospitality zoning', 'Road front'],
    description: 'Premium lakeside commercial land on Lake Kivu — hotel, restaurant, or mixed-use potential.',
    agentId: 'a2',
  },
  {
    id: 'p10',
    title: 'Rebero Heights Penthouse',
    type: 'apartment',
    mode: 'buy',
    status: 'reserved',
    price: 168_000_000,
    currency: 'RWF',
    location: 'Rebero',
    city: 'Kigali',
    country: 'Rwanda',
    builtArea: '220 m²',
    bedrooms: 3,
    bathrooms: 3,
    images: img('apartment', 'p10', 'Rebero Penthouse', 3),
    has360Tour: true,
    verified: true,
    trustScore: 95,
    specs: ['Panoramic view', 'Rooftop terrace', '2 parking'],
    description: 'Top-floor penthouse with sweeping views across Kigali valley.',
    agentId: 'a1',
  },
  {
    id: 'c1',
    title: 'Toyota Land Cruiser Prado TX-L',
    type: 'car',
    mode: 'buy',
    status: 'available',
    price: 48_500_000,
    currency: 'RWF',
    location: 'Kacyiru',
    city: 'Kigali',
    country: 'Rwanda',
    images: img('car', 'c1', 'Kacyiru', 3),
    has360Tour: false,
    verified: true,
    trustScore: 97,
    specs: ['4WD', 'Leather interior', 'Full service history', 'Rwanda registered'],
    description:
      'Rwanda\'s favourite luxury SUV — perfect for family and upcountry travel. Single owner, full Toyota Rwanda service.',
    agentId: 'a2',
    featured: true,
    ownerName: 'Jean-Bosco Ndayisaba',
    ownerPhone: '722445566',
    vehicle: {
      make: 'Toyota',
      model: 'Land Cruiser Prado',
      year: 2021,
      mileage: '42,000 km',
      transmission: 'automatic',
      fuel: 'Diesel',
      color: 'Pearl White',
    },
  },
  {
    id: 'c2',
    title: 'Mercedes-Benz E 200 AMG Line',
    type: 'car',
    mode: 'buy',
    status: 'available',
    price: 62_000_000,
    currency: 'RWF',
    location: 'Kimihurura',
    city: 'Kigali',
    country: 'Rwanda',
    images: img('car', 'c2', 'Kimihurura', 3),
    has360Tour: false,
    verified: true,
    trustScore: 98,
    specs: ['AMG styling', 'Panoramic roof', 'Certified pre-owned', 'Warranty'],
    description: 'Executive sedan in immaculate condition. Ideal for Kigali business and diplomatic use.',
    agentId: 'a1',
    featured: true,
    vehicle: {
      make: 'Mercedes-Benz',
      model: 'E 200',
      year: 2020,
      mileage: '28,500 km',
      transmission: 'automatic',
      fuel: 'Petrol',
      color: 'Obsidian Black',
    },
  },
  {
    id: 'c3',
    title: 'Toyota Hilux Double Cab 4x4',
    type: 'car',
    mode: 'buy',
    status: 'available',
    price: 38_900_000,
    currency: 'RWF',
    location: 'Kicukiro',
    city: 'Kigali',
    country: 'Rwanda',
    images: img('car', 'c3', 'Kicukiro', 3),
    has360Tour: false,
    verified: true,
    trustScore: 95,
    specs: ['Tow bar', 'Bed liner', '4x4', 'Fleet maintained'],
    description: 'Workhorse pickup trusted across Rwanda — construction, farming, and safari-ready.',
    agentId: 'a3',
    vehicle: {
      make: 'Toyota',
      model: 'Hilux',
      year: 2019,
      mileage: '67,000 km',
      transmission: 'manual',
      fuel: 'Diesel',
      color: 'Silver',
    },
  },
  {
    id: 'c4',
    title: 'Tesla Model 3 Long Range',
    type: 'car',
    mode: 'buy',
    status: 'available',
    price: 55_000_000,
    currency: 'RWF',
    location: 'Nyarutarama',
    city: 'Kigali',
    country: 'Rwanda',
    images: img('car', 'c4', 'Nyarutarama', 3),
    has360Tour: false,
    verified: true,
    trustScore: 96,
    specs: ['Autopilot', 'Home charger included', 'Low running cost', 'EV'],
    description: 'Rwanda\'s first premium electric sedan listing — zero emissions, silent luxury.',
    agentId: 'a1',
    vehicle: {
      make: 'Tesla',
      model: 'Model 3',
      year: 2022,
      mileage: '18,200 km',
      transmission: 'automatic',
      fuel: 'Electric',
      color: 'Midnight Silver',
    },
  },
  {
    id: 'c5',
    title: 'BMW X5 xDrive40i M Sport',
    type: 'car',
    mode: 'buy',
    status: 'available',
    price: 72_000_000,
    currency: 'RWF',
    location: 'Gacuriro',
    city: 'Kigali',
    country: 'Rwanda',
    images: img('car', 'c5', 'Gacuriro', 3),
    has360Tour: false,
    verified: true,
    trustScore: 97,
    specs: ['M Sport package', 'Harmon Kardon', 'Panoramic roof', 'xDrive'],
    description: 'Flagship luxury SUV for discerning buyers. Inspected and certified by Car House.',
    agentId: 'a2',
    vehicle: {
      make: 'BMW',
      model: 'X5',
      year: 2021,
      mileage: '35,000 km',
      transmission: 'automatic',
      fuel: 'Petrol',
      color: 'Carbon Black',
    },
  },
  {
    id: 'c6',
    title: 'Range Rover Sport HSE Dynamic',
    type: 'car',
    mode: 'buy',
    status: 'under_offer',
    price: 89_000_000,
    currency: 'RWF',
    location: 'Nyarutarama',
    city: 'Kigali',
    country: 'Rwanda',
    images: img('car', 'c6', 'Nyarutarama', 3),
    has360Tour: false,
    verified: true,
    trustScore: 99,
    specs: ['Air suspension', 'Meridian sound', 'Full LR service', 'Luxury SUV'],
    description: 'Top-tier British luxury SUV with verified import papers and full inspection report.',
    agentId: 'a1',
    vehicle: {
      make: 'Land Rover',
      model: 'Range Rover Sport',
      year: 2020,
      mileage: '41,000 km',
      transmission: 'automatic',
      fuel: 'Diesel',
      color: 'Santorini Black',
    },
  },
]

export const testimonials: Testimonial[] = [
  {
    id: 't1',
    name: 'Patrick Mugisha',
    role: 'Land Investor, Kigali',
    quote:
      'Under Innocent\'s leadership, Car House verified my Kicukiro plot boundaries against RDB records before I paid the deposit. The survey PDF gave me complete confidence.',
    avatar: agentAvatar('patrick-mugisha'),
    rating: 5,
  },
  {
    id: 't2',
    name: 'Claudine Umutoni',
    role: 'Diaspora Buyer, Belgium',
    quote:
      'Innocent Real Estate made buying from abroad simple — site visit booking, MTN MoMo payment, and WhatsApp updates every step of the way.',
    avatar: agentAvatar('claudine-umutoni'),
    rating: 5,
  },
  {
    id: 't3',
    name: 'David Okello',
    role: 'Commercial Developer, Kenya',
    quote:
      'The investor analytics on Nyarutarama and Kimihurura helped us compare ROI across districts. Professional, transparent, and premium.',
    avatar: agentAvatar('david-okello'),
    rating: 5,
  },
]

export const nearbyLocations = [
  { name: 'Kimihurura', count: 86, image: imageForLocation('Kimihurura', 800) },
  { name: 'Kacyiru', count: 124, image: imageForLocation('Kacyiru', 800) },
  { name: 'Kicukiro', count: 198, image: imageForLocation('Kicukiro', 800) },
  { name: 'Nyarutarama', count: 72, image: imageForLocation('Nyarutarama', 800) },
  { name: 'Remera', count: 156, image: imageForLocation('Remera', 800) },
  { name: 'Musanze', count: 45, image: imageForLocation('Musanze', 800) },
]

export const platformStats = [
  { label: 'Verified Listings', value: '1,240+' },
  { label: 'Districts Covered', value: '8' },
  { label: 'Avg. Trust Score', value: '94' },
  { label: 'Site Visits / Month', value: '320+' },
]

export function formatPrice(price: number, currency: string, mode?: 'buy' | 'rent'): string {
  if (currency === 'RWF') {
    return formatRWF(price, { monthly: mode === 'rent' })
  }
  if (price >= 1_000_000) return `${currency} ${(price / 1_000_000).toFixed(1)}M`
  if (price >= 1_000) return `${currency} ${(price / 1_000).toFixed(0)}K`
  return `${currency} ${price.toLocaleString()}`
}
