import type { Vehicle } from '@/types/vehicle'
import { imagesForVehicle } from '@/lib/images'
import { formatPrice } from '@/lib/mock-data'

const vimg = (id: string, body: string, n = 3) => imagesForVehicle(id, n, body)

export const vehicles: Vehicle[] = [
  {
    id: 'c1',
    title: 'Mercedes-Benz GLE 450 4MATIC',
    make: 'Mercedes-Benz',
    model: 'GLE 450',
    year: 2023,
    price: 89_500_000,
    currency: 'RWF',
    mileage: '18,200 km',
    transmission: 'automatic',
    fuel: 'Petrol',
    color: 'Obsidian Black',
    location: 'Kacyiru',
    city: 'Kigali',
    country: 'Rwanda',
    images: vimg('c1', 'suv'),
    verified: true,
    trustScore: 97,
    specs: ['Panoramic roof', 'Leather interior', '360° camera', 'Full service history'],
    description:
      'Immaculate GLE with dealer service records. Ideal for executives in Kigali — verified import papers and roadworthy certificate.',
    agentId: 'a1',
    featured: true,
    condition: 'certified',
    bodyType: 'suv',
    status: 'available',
  },
  {
    id: 'c2',
    title: 'Toyota Land Cruiser V8',
    make: 'Toyota',
    model: 'Land Cruiser',
    year: 2021,
    price: 125_000_000,
    currency: 'RWF',
    mileage: '42,000 km',
    transmission: 'automatic',
    fuel: 'Diesel',
    color: 'Pearl White',
    location: 'Kimihurura',
    city: 'Kigali',
    country: 'Rwanda',
    images: vimg('c2', 'suv'),
    verified: true,
    trustScore: 96,
    specs: ['7 seats', '4WD', 'Cool box', 'New tyres'],
    description:
      'Rwanda\'s favourite luxury SUV — perfect for family and upcountry travel. Single owner, full Toyota Rwanda service.',
    agentId: 'a2',
    featured: true,
    condition: 'used',
    bodyType: 'suv',
    status: 'available',
  },
  {
    id: 'c3',
    title: 'BMW 530i M Sport',
    make: 'BMW',
    model: '530i',
    year: 2022,
    price: 52_800_000,
    currency: 'RWF',
    mileage: '24,500 km',
    transmission: 'automatic',
    fuel: 'Petrol',
    color: 'Alpine White',
    location: 'Nyarutarama',
    city: 'Kigali',
    country: 'Rwanda',
    images: vimg('c3', 'sedan'),
    verified: true,
    trustScore: 95,
    specs: ['M Sport pack', 'Harmon Kardon', 'Adaptive cruise', 'Wireless CarPlay'],
    description: 'Executive sedan in pristine condition. Verified VIN, no accident history.',
    agentId: 'a1',
    featured: true,
    condition: 'certified',
    bodyType: 'luxury',
    status: 'available',
  },
  {
    id: 'c4',
    title: 'Tesla Model 3 Long Range',
    make: 'Tesla',
    model: 'Model 3',
    year: 2024,
    price: 68_000_000,
    currency: 'RWF',
    mileage: '8,100 km',
    transmission: 'automatic',
    fuel: 'Electric',
    color: 'Midnight Silver',
    location: 'Kacyiru',
    city: 'Kigali',
    country: 'Rwanda',
    images: vimg('c4', 'electric'),
    verified: true,
    trustScore: 98,
    specs: ['Autopilot', 'Heat pump', 'Home charger included', '8-year battery warranty'],
    description: 'Rwanda\'s premium EV — low running costs, zero emissions, ideal for Kigali commutes.',
    agentId: 'a3',
    featured: true,
    condition: 'new',
    bodyType: 'electric',
    status: 'available',
  },
  {
    id: 'c5',
    title: 'Toyota Hilux Double Cab 4x4',
    make: 'Toyota',
    model: 'Hilux',
    year: 2020,
    price: 38_500_000,
    currency: 'RWF',
    mileage: '67,000 km',
    transmission: 'manual',
    fuel: 'Diesel',
    color: 'Graphite',
    location: 'Remera',
    city: 'Kigali',
    country: 'Rwanda',
    images: vimg('c5', 'pickup'),
    verified: true,
    trustScore: 93,
    specs: ['Snorkel ready', 'Tow bar', 'Bed liner', 'Work-ready'],
    description: 'Reliable Hilux for business and adventure. RRA-registered, road tax paid.',
    agentId: 'a2',
    featured: false,
    condition: 'used',
    bodyType: 'pickup',
    status: 'available',
  },
  {
    id: 'c6',
    title: 'Range Rover Sport HSE',
    make: 'Land Rover',
    model: 'Range Rover Sport',
    year: 2022,
    price: 142_000_000,
    currency: 'RWF',
    mileage: '31,000 km',
    transmission: 'automatic',
    fuel: 'Hybrid',
    color: 'Santorini Black',
    location: 'Kimihurura',
    city: 'Kigali',
    country: 'Rwanda',
    images: vimg('c6', 'luxury'),
    verified: true,
    trustScore: 97,
    specs: ['Air suspension', 'Meridian sound', 'Heated/cooled seats', 'Full dealer history'],
    description: 'Flagship luxury SUV for discerning buyers. Inspected and certified by Car House.',
    agentId: 'a1',
    featured: true,
    condition: 'certified',
    bodyType: 'luxury',
    status: 'available',
  },
]

export function formatVehiclePrice(vehicle: Vehicle): string {
  return formatPrice(vehicle.price, vehicle.currency)
}

export const featuredVehicles = vehicles.filter((v) => v.featured)
